name: Regress

on: [workflow_dispatch, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: norio-nomura/action-swiftlint@3.2.1
      with: { args: --strict }

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with: { xcode-version: '14.1' }
    # https://github.com/actions/runner-images/issues/1665
    - name: Build RugbyPlanner
      run: |
        brew install xcbeautify
        xcodebuild \
          -project RugbyPlanner.xcodeproj \
          -scheme RugbyPlanner \
          -configuration Release \
          -derivedDataPath build \
          -skipPackagePluginValidation | xcbeautify
        lipo -i build/Build/Products/Release/RugbyPlanner.app/Contents/MacOS/RugbyPlanner
        echo "artifact_path=build/Build/Products/Release/RugbyPlanner.app" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: RugbyPlanner
        path: ${{ env.artifact_path }}
        if-no-files-found: error
        retention-days: 1
